### ISSUE TITLE
Missing important sites from Interview Questions sections

### ISSUE THREAD

**Issue by sagnik20** [S-ayanide/Competitive-Coding#1]
Hey!
On the Interview Questions section, you missed adding [LeetCode](https://leetcode.com/) and [CodeChef](https://www.codechef.com/) which are two of the most important sites for Competitive Coding and Interview preparation.

If you allow I can make a pull request by adding those.

Thanks 😃

**Comment by S-ayanide** [comment]
Hello @sagnik20 , 
If you take a look into the **Sites for Practice** section you can find [CodeChef](https://github.com/S-ayanide/Competitive-Coding#sites-for-practice) there. Because [CodeChef](https://www.codechef.com/) is more of a contest platform rather than a niche focus just on Interview questions and preparation, we thought its best put in the category of Coding Practice.

However you can make a pull request to add [LeetCode in the #Interview Questions](https://github.com/S-ayanide/Competitive-Coding#interview-questions) section. 

I believe this issue stands resolved.
